### ISSUE TITLE
Final TODO before release

### ISSUE THREAD

**Issue by NullVoxPopuli** [NullVoxPopuli/aeonvera#559]
Grouping these all in to one issue, so I don't continue bloating my issue count.

- [x] Persist Housing Requests (#536)
- [x] Persist Housing Provisions (#536)
- [x] Persist Custom Field responses (#536)
- [x] Re-Test Organization Registration workflow
- [x] Test Event Registration workflow
- [x] Figure out difference between update / pay (do they even need to remain different? (no))
- [x] Scrap updating with embedded objects. Order Line Items should get their own Controller actions after the order is created.
- [ ] Make sure cancelled attendances aren't included in item summaries (#337)
- [ ] Re-Test at the door workflows (#541 and #268)
- [x] Double check the payment / stripe logic
